citation("lme4")
citation("FD")
citation("picante")
citation("PCPS")
citation("vegan")
citation("corrplot")
citation("car")
citation("lmerTest")
citation("MuMIn")
citation("AIC")
citation("lavaan")
citation("corrplot")
citation("lavaan")
citation("lavaan")
citation("lavaan")
citation()
R.version.string

